/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author lenny
 */
public class Creditos extends javax.swing.JFrame {

    FondoGame1 fondo = new FondoGame1();

    public Creditos() {
        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHome = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblCesar = new javax.swing.JLabel();
        lblMiguel = new javax.swing.JLabel();
        lblLenny = new javax.swing.JLabel();
        lblAris = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 525));
        setUndecorated(true);
        setSize(new java.awt.Dimension(950, 525));
        getContentPane().setLayout(null);

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        getContentPane().add(lblHome);
        lblHome.setBounds(16, 467, 40, 40);

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Close.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar);
        lblCerrar.setBounds(915, 6, 29, 29);

        lblCesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cesar.png"))); // NOI18N
        getContentPane().add(lblCesar);
        lblCesar.setBounds(449, 56, 160, 174);

        lblMiguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Miguel.png"))); // NOI18N
        getContentPane().add(lblMiguel);
        lblMiguel.setBounds(449, 248, 160, 174);

        lblLenny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lenny.png"))); // NOI18N
        getContentPane().add(lblLenny);
        lblLenny.setBounds(47, 248, 160, 174);

        lblAris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aristides.png"))); // NOI18N
        getContentPane().add(lblAris);
        lblAris.setBounds(47, 56, 160, 174);

        jLabel1.setText("Josue Aristides");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(213, 76, 187, 16);

        jLabel2.setText("Melendez Aleman");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(213, 110, 187, 16);

        jLabel3.setText("Elias Sanchez");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 310, 187, 16);

        jLabel4.setText("Cesar ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(630, 310, 187, 16);

        jLabel5.setText("Lenny Adrian");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(213, 273, 187, 16);

        jLabel6.setText("Cesar ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(630, 80, 187, 16);

        jLabel7.setText("Cesar ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(670, 150, 110, 16);

        jLabel8.setText("Cesar ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 270, 187, 16);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(650, 130, 190, 114);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        Inicio menu = new Inicio();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creditos().setVisible(true);
            }
        });
    }
    
    private class FondoGame1 extends JPanel {
        public Image imagen;
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Space1.gif")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAris;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCesar;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLenny;
    private javax.swing.JLabel lblMiguel;
    // End of variables declaration//GEN-END:variables
}
