/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import Tipografia.Fuente;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author César, Lenny, Aristides, Miguel
 */
public class Creditos extends javax.swing.JFrame {

    FondoGame1 fondo = new FondoGame1();
    Fuente TipoFuente = new Fuente();
    
    
    public Creditos() {
        this.setContentPane(fondo);
        initComponents();
        jLblNombreJosue.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        jLblApellidoJosue.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        jLblTipoJosue.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        
        jLblNombreLenny.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        jLblApellidoLenny.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        jLblTipoLenny.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        
        jLblNombreMiguel.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        jLblApellidoMiguel.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        jLblTipoMiguel.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        
        jLblNombreCesar.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        jLblApellidoCesar.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        jLblTipoCesar.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        
        /*Utilizamos new ImageIcon(URL location).getImage() donde el argumento
        *location lo obtenemos a través del método getClass().getResource(String name)
        *que nos devuelve un URL absoluto del recurso que especificamos como String.
        */
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/SpaceChemistryIcon.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLblTipoJosue = new javax.swing.JLabel();
        jLblNombreJosue = new javax.swing.JLabel();
        jLblApellidoJosue = new javax.swing.JLabel();
        lblAris = new javax.swing.JLabel();
        jLabelJosue = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLenny = new javax.swing.JLabel();
        jLblNombreLenny = new javax.swing.JLabel();
        jLblTipoLenny = new javax.swing.JLabel();
        jLblApellidoLenny = new javax.swing.JLabel();
        jLabelJosue1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblMiguel = new javax.swing.JLabel();
        jLblApellidoMiguel = new javax.swing.JLabel();
        jLblNombreMiguel = new javax.swing.JLabel();
        jLblTipoMiguel = new javax.swing.JLabel();
        jLabelJosue2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblCesar = new javax.swing.JLabel();
        jLblTipoCesar = new javax.swing.JLabel();
        jLblApellidoCesar = new javax.swing.JLabel();
        jLblNombreCesar = new javax.swing.JLabel();
        jLabelJosue3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 525));
        setUndecorated(true);
        setSize(new java.awt.Dimension(950, 525));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 470, 40, 40);

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Close.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar);
        lblCerrar.setBounds(915, 6, 29, 29);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(890, 92, 0, 0);

        jPanel1.setLayout(null);

        jLblTipoJosue.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblTipoJosue.setForeground(new java.awt.Color(255, 255, 255));
        jLblTipoJosue.setText("-Programador");
        jPanel1.add(jLblTipoJosue);
        jLblTipoJosue.setBounds(260, 120, 100, 20);

        jLblNombreJosue.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblNombreJosue.setForeground(new java.awt.Color(255, 255, 255));
        jLblNombreJosue.setText("Josue Aristides ");
        jPanel1.add(jLblNombreJosue);
        jLblNombreJosue.setBounds(200, 70, 150, 20);

        jLblApellidoJosue.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblApellidoJosue.setForeground(new java.awt.Color(255, 255, 255));
        jLblApellidoJosue.setText("Melendez Aleman");
        jPanel1.add(jLblApellidoJosue);
        jLblApellidoJosue.setBounds(200, 90, 150, 20);

        lblAris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aristides.png"))); // NOI18N
        jPanel1.add(lblAris);
        lblAris.setBounds(6, 6, 160, 174);

        jLabelJosue.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelJosue.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJosue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TGamePanel.png"))); // NOI18N
        jLabelJosue.setToolTipText("");
        jLabelJosue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelJosue);
        jLabelJosue.setBounds(172, 40, 200, 119);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(72, 73, 420, 180);

        jPanel2.setLayout(null);

        lblLenny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lenny.png"))); // NOI18N
        jPanel2.add(lblLenny);
        lblLenny.setBounds(6, 6, 160, 174);

        jLblNombreLenny.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblNombreLenny.setForeground(new java.awt.Color(255, 255, 255));
        jLblNombreLenny.setText("Lenny Adrian");
        jPanel2.add(jLblNombreLenny);
        jLblNombreLenny.setBounds(200, 70, 150, 20);

        jLblTipoLenny.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblTipoLenny.setForeground(new java.awt.Color(255, 255, 255));
        jLblTipoLenny.setText("-Disenador y Programador");
        jPanel2.add(jLblTipoLenny);
        jLblTipoLenny.setBounds(190, 120, 180, 20);

        jLblApellidoLenny.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblApellidoLenny.setForeground(new java.awt.Color(255, 255, 255));
        jLblApellidoLenny.setText("Elias Sanchez");
        jPanel2.add(jLblApellidoLenny);
        jLblApellidoLenny.setBounds(200, 90, 150, 20);

        jLabelJosue1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelJosue1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJosue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TGamePanel.png"))); // NOI18N
        jLabelJosue1.setToolTipText("");
        jLabelJosue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabelJosue1);
        jLabelJosue1.setBounds(170, 40, 200, 119);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(72, 271, 380, 190);

        jPanel3.setLayout(null);

        lblMiguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Miguel.png"))); // NOI18N
        jPanel3.add(lblMiguel);
        lblMiguel.setBounds(6, 6, 160, 174);

        jLblApellidoMiguel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblApellidoMiguel.setForeground(new java.awt.Color(255, 255, 255));
        jLblApellidoMiguel.setText("Hernandez Martinez");
        jPanel3.add(jLblApellidoMiguel);
        jLblApellidoMiguel.setBounds(190, 90, 150, 20);

        jLblNombreMiguel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblNombreMiguel.setForeground(new java.awt.Color(255, 255, 255));
        jLblNombreMiguel.setText("Miguel Alexander");
        jPanel3.add(jLblNombreMiguel);
        jLblNombreMiguel.setBounds(190, 70, 150, 20);

        jLblTipoMiguel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblTipoMiguel.setForeground(new java.awt.Color(255, 255, 255));
        jLblTipoMiguel.setText("-Programador");
        jPanel3.add(jLblTipoMiguel);
        jLblTipoMiguel.setBounds(250, 120, 100, 20);

        jLabelJosue2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelJosue2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJosue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TGamePanel.png"))); // NOI18N
        jLabelJosue2.setToolTipText("");
        jLabelJosue2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabelJosue2);
        jLabelJosue2.setBounds(160, 40, 200, 119);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(482, 271, 370, 170);

        jPanel4.setLayout(null);

        lblCesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cesar.png"))); // NOI18N
        jPanel4.add(lblCesar);
        lblCesar.setBounds(10, 0, 160, 174);

        jLblTipoCesar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblTipoCesar.setForeground(new java.awt.Color(255, 255, 255));
        jLblTipoCesar.setText("-Programador ");
        jPanel4.add(jLblTipoCesar);
        jLblTipoCesar.setBounds(250, 120, 100, 20);

        jLblApellidoCesar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblApellidoCesar.setForeground(new java.awt.Color(255, 255, 255));
        jLblApellidoCesar.setText("Flores Martinez");
        jPanel4.add(jLblApellidoCesar);
        jLblApellidoCesar.setBounds(190, 90, 150, 20);

        jLblNombreCesar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblNombreCesar.setForeground(new java.awt.Color(255, 255, 255));
        jLblNombreCesar.setText("Cesar Esau");
        jPanel4.add(jLblNombreCesar);
        jLblNombreCesar.setBounds(190, 70, 150, 20);

        jLabelJosue3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelJosue3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJosue3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TGamePanel.png"))); // NOI18N
        jLabelJosue3.setToolTipText("");
        jLabelJosue3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabelJosue3);
        jLabelJosue3.setBounds(160, 40, 200, 119);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(480, 70, 360, 170);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Inicio menu = new Inicio();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creditos().setVisible(true);
            }
        });
    }
    
    private class FondoGame1 extends JPanel {
        public Image imagen;
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Space1.gif")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            jPanel1.setOpaque(false);
            jPanel2.setOpaque(false);
            jPanel3.setOpaque(false);
            jPanel4.setOpaque(false);
            
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelJosue;
    private javax.swing.JLabel jLabelJosue1;
    private javax.swing.JLabel jLabelJosue2;
    private javax.swing.JLabel jLabelJosue3;
    private javax.swing.JLabel jLblApellidoCesar;
    private javax.swing.JLabel jLblApellidoJosue;
    private javax.swing.JLabel jLblApellidoLenny;
    private javax.swing.JLabel jLblApellidoMiguel;
    private javax.swing.JLabel jLblNombreCesar;
    private javax.swing.JLabel jLblNombreJosue;
    private javax.swing.JLabel jLblNombreLenny;
    private javax.swing.JLabel jLblNombreMiguel;
    private javax.swing.JLabel jLblTipoCesar;
    private javax.swing.JLabel jLblTipoJosue;
    private javax.swing.JLabel jLblTipoLenny;
    private javax.swing.JLabel jLblTipoMiguel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAris;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCesar;
    private javax.swing.JLabel lblLenny;
    private javax.swing.JLabel lblMiguel;
    // End of variables declaration//GEN-END:variables
}
