/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import Tipografia.Fuente;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Lenny
 */
public class Creditos extends javax.swing.JFrame {

    FondoGame1 fondo = new FondoGame1();
    Fuente TipoFuente = new Fuente();

    public Creditos() {
        this.setContentPane(fondo);
        initComponents();

        jLblNombreLenny.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        jLblApellidoLenny.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        jLblTipoLenny.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));

        Image icon = new ImageIcon(getClass().getResource("/Imagenes/SpaceChemistryIcon.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLenny = new javax.swing.JLabel();
        jLblNombreLenny = new javax.swing.JLabel();
        jLblTipoLenny = new javax.swing.JLabel();
        jLblApellidoLenny = new javax.swing.JLabel();
        jLabelJosue1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 525));
        setUndecorated(true);
        setSize(new java.awt.Dimension(950, 525));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 470, 40, 40);

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Close.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar);
        lblCerrar.setBounds(915, 6, 29, 29);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(890, 92, 0, 0);

        jPanel2.setLayout(null);

        lblLenny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lenny.png"))); // NOI18N
        jPanel2.add(lblLenny);
        lblLenny.setBounds(6, 6, 160, 174);

        jLblNombreLenny.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblNombreLenny.setForeground(new java.awt.Color(255, 255, 255));
        jLblNombreLenny.setText("Lenny Adrian");
        jPanel2.add(jLblNombreLenny);
        jLblNombreLenny.setBounds(200, 70, 150, 20);

        jLblTipoLenny.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblTipoLenny.setForeground(new java.awt.Color(255, 255, 255));
        jLblTipoLenny.setText("-Disenador y Programador");
        jPanel2.add(jLblTipoLenny);
        jLblTipoLenny.setBounds(190, 120, 180, 20);

        jLblApellidoLenny.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLblApellidoLenny.setForeground(new java.awt.Color(255, 255, 255));
        jLblApellidoLenny.setText("Elias Sanchez");
        jPanel2.add(jLblApellidoLenny);
        jLblApellidoLenny.setBounds(200, 90, 150, 20);

        jLabelJosue1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelJosue1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJosue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TGamePanel.png"))); // NOI18N
        jLabelJosue1.setToolTipText("");
        jLabelJosue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabelJosue1);
        jLabelJosue1.setBounds(170, 40, 200, 119);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(285, 170, 380, 190);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Inicio menu = new Inicio();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creditos().setVisible(true);
            }
        });
    }

    private class FondoGame1 extends JPanel {
        public Image imagen;
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Space1.gif")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            jPanel2.setOpaque(false);

            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelJosue1;
    private javax.swing.JLabel jLblApellidoLenny;
    private javax.swing.JLabel jLblNombreLenny;
    private javax.swing.JLabel jLblTipoLenny;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblLenny;
    // End of variables declaration//GEN-END:variables
}
