/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import Tipografia.Fuente;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author lenny
 */
public class FrmAyuda extends javax.swing.JFrame {

    FondoGameAyuda fondo = new FondoGameAyuda();
    Fuente TipoFuente = new Fuente();
    
    public FrmAyuda() {
        this.setContentPane(fondo);
        initComponents();
        
        PanelCompuestos.setBackground(new Color(0,0,0,0));
        
        PanelElementos.setVisible(false);
        PanelCompuestos.setVisible(true);
        TARecoleccion.setEditable(false);
        TAPuBalas.setEditable(false);
        TAPuVelocidad.setEditable(false);
        TAInfo1.setEditable(false);
        lblIzquierda.setVisible(false);
        
        TAPuBalas.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        TAPuVelocidad.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        TAInfo1.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        TARecoleccion.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        TAPuBalas.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        TAPuVelocidad.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        TAInfo1.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        lblMover.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        lblDisparar.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        lblELIMINAR.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 9));
        lblESC.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 9));
        lblNiveles.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));
        lblVida.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 10));    
        
        PanelElementos.setBackground(new Color(0,0,0,0));
        /*Utilizamos new ImageIcon(URL location).getImage() donde el argumento
        *location lo obtenemos a través del método getClass().getResource(String name)
        *que nos devuelve un URL absoluto del recurso que especificamos como String.
        */
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/SpaceChemistryIcon.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCerrar = new javax.swing.JLabel();
        lblDerecha = new javax.swing.JLabel();
        lblIzquierda = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        PanelCompuestos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TAPuBalas = new javax.swing.JTextArea();
        lblImagen2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TAPuVelocidad = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TAInfo1 = new javax.swing.JTextArea();
        lblDisparar = new javax.swing.JLabel();
        lblMover = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblVida = new javax.swing.JLabel();
        lblESC = new javax.swing.JLabel();
        lblNiveles = new javax.swing.JLabel();
        lblELIMINAR = new javax.swing.JLabel();
        PanelElementos = new javax.swing.JPanel();
        lblImagen1 = new javax.swing.JLabel();
        lblTabla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TARecoleccion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 525));
        setMinimumSize(new java.awt.Dimension(950, 525));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 525));
        setSize(new java.awt.Dimension(950, 525));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Close.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/derecha.png"))); // NOI18N
        lblDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDerechaMouseClicked(evt);
            }
        });

        lblIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Izquierda.png"))); // NOI18N
        lblIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIzquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIzquierdaMouseClicked(evt);
            }
        });

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        PanelCompuestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        PanelCompuestos.setMaximumSize(new java.awt.Dimension(760, 440));
        PanelCompuestos.setMinimumSize(new java.awt.Dimension(760, 440));
        PanelCompuestos.setPreferredSize(new java.awt.Dimension(760, 440));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TAPuBalas.setColumns(20);
        TAPuBalas.setRows(5);
        TAPuBalas.setText("1.La parte Superior con \nletras rojas, en esta\nseccion nos dan\nuna mejora en la \ncantidad de balas\nque puede disparar\nla nave.\n\nEsta ordenado de forma\nascendente, siendo Fe\nel compuesto mas\ndebil.\n\nEsta mejora es \npermanente ");
        jScrollPane4.setViewportView(TAPuBalas);

        lblImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Power Ups.png"))); // NOI18N

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setToolTipText("");
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TAPuVelocidad.setColumns(20);
        TAPuVelocidad.setRows(5);
        TAPuVelocidad.setText("3.La parte Inferior con\nletras Moradas, es la\nseccion para mejorar\nla velocidad de la\nnave.\n\nEsta ordenado de forma\nascendente, siendo He\nel compuesto mas\ndebil.\n\nEsta mejora no es \npermanente");
        jScrollPane5.setViewportView(TAPuVelocidad);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha2.png"))); // NOI18N

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setToolTipText("");
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TAInfo1.setColumns(20);
        TAInfo1.setRows(5);
        TAInfo1.setText("2.Las teclas en negro\nque estan en \nvertical\n(F,W,O,U,Z, T, H\nN, S, B, P, A) deben \nde presionarse para\nactivar el Power Up.");
        jScrollPane6.setViewportView(TAInfo1);

        lblDisparar.setBackground(new java.awt.Color(255, 255, 255));
        lblDisparar.setForeground(new java.awt.Color(255, 255, 255));
        lblDisparar.setText("Disparar: ");

        lblMover.setBackground(new java.awt.Color(255, 255, 255));
        lblMover.setForeground(new java.awt.Color(0, 0, 0));
        lblMover.setText("Mover Nave:");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Left&Right.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SpaceBar.png"))); // NOI18N

        lblVida.setBackground(new java.awt.Color(255, 255, 255));
        lblVida.setForeground(new java.awt.Color(255, 255, 255));
        lblVida.setText("Vida del Jefe: 45");

        lblESC.setBackground(new java.awt.Color(255, 255, 255));
        lblESC.setForeground(new java.awt.Color(255, 255, 255));
        lblESC.setText("Presionar ESC para Pausar el Juego");

        lblNiveles.setBackground(new java.awt.Color(255, 255, 255));
        lblNiveles.setForeground(new java.awt.Color(255, 255, 255));
        lblNiveles.setText("Niveles: 15");

        lblELIMINAR.setBackground(new java.awt.Color(255, 255, 255));
        lblELIMINAR.setForeground(new java.awt.Color(0, 0, 0));
        lblELIMINAR.setText("Eliminar Naves antes de que entren a la Atmosfera de la Tierra");

        javax.swing.GroupLayout PanelCompuestosLayout = new javax.swing.GroupLayout(PanelCompuestos);
        PanelCompuestos.setLayout(PanelCompuestosLayout);
        PanelCompuestosLayout.setHorizontalGroup(
            PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCompuestosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCompuestosLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelCompuestosLayout.createSequentialGroup()
                            .addComponent(lblDisparar)
                            .addGap(24, 24, 24)
                            .addComponent(jLabel6))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCompuestosLayout.createSequentialGroup()
                            .addComponent(lblMover)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblVida)
                    .addComponent(lblESC)
                    .addComponent(lblNiveles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelCompuestosLayout.createSequentialGroup()
                        .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCompuestosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblELIMINAR))
                .addGap(45, 45, 45))
        );
        PanelCompuestosLayout.setVerticalGroup(
            PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCompuestosLayout.createSequentialGroup()
                .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCompuestosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCompuestosLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisparar)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMover)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelCompuestosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCompuestosLayout.createSequentialGroup()
                        .addComponent(lblImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelCompuestosLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCompuestosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184))
                            .addGroup(PanelCompuestosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVida)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNiveles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelCompuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblESC)
                                    .addComponent(lblELIMINAR))
                                .addContainerGap(13, Short.MAX_VALUE))))))
        );

        PanelElementos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));
        PanelElementos.setMaximumSize(new java.awt.Dimension(760, 440));
        PanelElementos.setMinimumSize(new java.awt.Dimension(760, 440));
        PanelElementos.setPreferredSize(new java.awt.Dimension(760, 440));

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Conteo.png"))); // NOI18N

        lblTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PowerUpsTabla.png"))); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TARecoleccion.setColumns(20);
        TARecoleccion.setRows(5);
        TARecoleccion.setText("4.En la parte inferior\ndel panel de \nElementos del\nJuego, se realizara\nun conteo de los\nelementos \nrecolectados por\nel jugador.\n\nA veces cae un\ncirculo rojo +1:\nrecogerlo da una\nvida extra (raro).");
        jScrollPane1.setViewportView(TARecoleccion);

        javax.swing.GroupLayout PanelElementosLayout = new javax.swing.GroupLayout(PanelElementos);
        PanelElementos.setLayout(PanelElementosLayout);
        PanelElementosLayout.setHorizontalGroup(
            PanelElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelElementosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(lblTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        PanelElementosLayout.setVerticalGroup(
            PanelElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelElementosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelElementosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelElementosLayout.createSequentialGroup()
                        .addComponent(lblImagen1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(900, 900, 900)
                .addComponent(lblCerrar))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIzquierda)
                    .addComponent(lblHome))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelElementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelCompuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(lblDerecha))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCerrar)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelElementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelCompuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIzquierda)
                            .addComponent(lblDerecha))
                        .addGap(132, 132, 132)
                        .addComponent(lblHome)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        Inicio menu = new Inicio();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDerechaMouseClicked
        lblIzquierda.setVisible(true);
        lblDerecha.setVisible(false);
        PanelElementos.setVisible(true);
        PanelCompuestos.setVisible(false);
    }//GEN-LAST:event_lblDerechaMouseClicked

    private void lblIzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIzquierdaMouseClicked
        lblDerecha.setVisible(true);
        lblIzquierda.setVisible(false);
        PanelElementos.setVisible(false);
        PanelCompuestos.setVisible(true);
    }//GEN-LAST:event_lblIzquierdaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAyuda().setVisible(true);
            }
        });
    }
    
    private class FondoGameAyuda extends JPanel {
        public Image imagen;
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Space1.gif")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCompuestos;
    private javax.swing.JPanel PanelElementos;
    private javax.swing.JTextArea TAInfo1;
    private javax.swing.JTextArea TAPuBalas;
    private javax.swing.JTextArea TAPuVelocidad;
    private javax.swing.JTextArea TARecoleccion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblDerecha;
    private javax.swing.JLabel lblDisparar;
    private javax.swing.JLabel lblELIMINAR;
    private javax.swing.JLabel lblESC;
    public volatile javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblIzquierda;
    private javax.swing.JLabel lblMover;
    private javax.swing.JLabel lblNiveles;
    private javax.swing.JLabel lblTabla;
    private javax.swing.JLabel lblVida;
    // End of variables declaration//GEN-END:variables
}
