/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import Tipografia.Fuente;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Shape;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author lenny
 */
public class Victoria extends javax.swing.JFrame {

    private SoundEffect finSoundAudio;
    FondoGame fondo = new FondoGame();
    Fuente TipoFuente = new Fuente();
    Color GrisGame = new Color(153,153,153);
    Color CelesteGame = new Color(40, 255, 240);
    Color LetrasAzul = new Color(31,75,142);
    public int score = 0;

    public Victoria() {
        this.setContentPane(fondo);
        initComponents();
        
        try{
            finSoundAudio = SoundEffect.load("/Sonidos/Ending.wav");
            finSoundAudio.play();
        }
        catch(Exception e){}
        
        Inicio.PararJuego();
        
        lblSalvado.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 1, 16));
        lblScore.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 1, 16));
        btnFin.setFont(TipoFuente.fuenteSpace(TipoFuente.SpaceInvaders, 0, 14));
        
        Victoria.ShapedButtonUI squareUI = new Victoria.ShapedButtonUI();
        squareUI.setShape(Victoria.ButtonShape.SQUARE, btnFin);
        btnFin.setUI(squareUI);
        btnFin.setPreferredSize(new Dimension(100, 100));
        
        /*Utilizamos new ImageIcon(URL location).getImage() donde el argumento
        *location lo obtenemos a través del método getClass().getResource(String name)
        *que nos devuelve un URL absoluto del recurso que especificamos como String.
        */
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/SpaceChemistryIcon.png")).getImage();
        setIconImage(icon);
    }

    /**
    * Definimos la forma cuadrada
    */
    public enum ButtonShape {
        SQUARE
    }
    
    private class ShapedButtonUI extends BasicButtonUI {
        /** Button shape. */
        private ButtonShape shape;

        public ShapedButtonUI() {
            super();
        }

        public void setShape(ButtonShape shape, JButton button){
            // no pintamos el borde
            button.setBorderPainted(false);
            this.shape = shape;
        }

        public void paint(JComponent c) {
            // definamos las formas de nuestros botones
            Shape buttonShape = null;
            switch (shape) {
                case SQUARE:
                    buttonShape = new Rectangle(0, 0, c.getWidth(), c.getHeight());
                break;
            }
        }

        protected void paintButtonPressed(AbstractButton b) {
            // definamos las formas de nuestros botones
            Shape buttonShape = null;
            switch (shape) {
                case SQUARE:
                buttonShape = new Rectangle(0, 0, b.getWidth(), b.getHeight());
            break;
            }
        }
    }
    
    public void AsignarScore(int Score){
        score = Score;
        lblScore.setText("con " + Integer.toString(Score) + " puntos!"  );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnFin = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        lblSalvado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 675));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 675));
        getContentPane().setLayout(null);

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Close.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrar);
        lblCerrar.setBounds(965, 6, 29, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YouWin.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 400, 118);

        btnFin.setBackground(new java.awt.Color(153, 153, 153));
        btnFin.setForeground(new java.awt.Color(255, 255, 255));
        btnFin.setText("Regresar al menu");
        btnFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinMouseExited(evt);
            }
        });
        getContentPane().add(btnFin);
        btnFin.setBounds(680, 570, 230, 70);

        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setText("CON X PUNTOS!");
        getContentPane().add(lblScore);
        lblScore.setBounds(630, 320, 340, 60);

        lblSalvado.setForeground(new java.awt.Color(255, 255, 255));
        lblSalvado.setText("HAS SALVADO A LA HUMANIDAD! ");
        getContentPane().add(lblSalvado);
        lblSalvado.setBounds(630, 240, 340, 90);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void btnFinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinMouseClicked
        if (finSoundAudio != null) {
            finSoundAudio.stop();
        }
        this.dispose();
        
        Inicio menu = new Inicio();
        menu.setVisible(true);
    }//GEN-LAST:event_btnFinMouseClicked

    private void btnFinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinMouseEntered
        btnFin.setBackground(CelesteGame);
        btnFin.setForeground(LetrasAzul);
    }//GEN-LAST:event_btnFinMouseEntered

    private void btnFinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinMouseExited
        btnFin.setBackground(GrisGame);
        btnFin.setForeground(Color.white);
    }//GEN-LAST:event_btnFinMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Victoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Victoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Victoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Victoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Victoria().setVisible(true);
            }
        });
    }
    
    private class FondoGame extends JPanel {
        public Image imagen;
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Victory.gif")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblSalvado;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}
